spring.application.name=prod-ready-feature
spring.datasource.url=jdbc:mysql://localhost:3306/prod-ready-features
spring.datasource.username=root
spring.datasource.password=Pushpak@12345

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

hospitalManagementBaseUrl=http://localhost:9000
secretKey=adf66876asdf128asfkh900jjhgbbmnethlgh
management.endpoints.web.exposure.include=* 
