# Local Development Profile - Uses Testcontainers MSSQL
spring.datasource.url=jdbc:tc:sqlserver:///mssql?imageName=mcr.microsoft.com/mssql/server:8080-latest
spring.datasource.username=root
spring.datasource.password=pushpjal-123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
