spring.application.name=prod-ready-feature

# Default active profile (can be overridden with --spring.profiles.active=<profile>)
#spring.profiles.active=local

#
## For development (RDS)
#spring.profiles.active=dev
#
## For production (RDS)
spring.profiles.active=prod

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#spring.jpa.properties.hibernate.format_sql=true

hospitalManagementBaseUrl=http://localhost:9000
secretKey=adf66876asdf128asfkh900jjhgbbmnethlgh
management.endpoints.web.exposure.include=*